- type: entity
  abstract: true
  parent: STBaseStructure
  id: STBaseWall
  suffix: Wall
  placement:
    mode: SnapgridCenter
    snap:
    - Wall
  components:
  - type: RangedDamageSound
    soundGroups:
      Brute:
        collection:
          MetalBulletImpact
    soundTypes:
      Heat:
        collection:
          MetalLaserImpact
  - type: Tag
    tags:
    - Wall
  - type: Sprite
    drawdepth: Mobs
  - type: Icon
    state: full
  - type: PlacementReplacement
    key: walls
  - type: IconSmooth
    key: walls
    base: state
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Wood
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.5,-0.5,0.5,0.5"
        mask:
        - FullTileMask
        layer:
        - WallLayer
        density: 1000
  - type: Occluder
  - type: BlockWeather

